cache:
  url: "redis://{{ cookiecutter.cache_hostname }}:{{ cookiecutter.cache_port }}/0"
db:
  url: "postgresql://{{ cookiecutter.database_username }}:{{ cookiecutter.database_password }}@{{ cookiecutter.database_hostname }}:{{ cookiecutter.database_port }}/{{ cookiecutter.database_name }}"
