version: '3.8'
services:
  app:
    build: .
    networks:
      - {{cookiecutter.network_name}}
    volumes:
      - .:/app
    ports:
      - "{{cookiecutter.network_mapped_port}}:{{cookiecutter.network_container_port}}"
    environment:
      DOCKER: 1
    depends_on:
      postgres-setup:
        condition: service_completed_successfully

  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"
    networks:
      - {{cookiecutter.network_name}}
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-setup:
    image: pgvector/pgvector:pg16
    networks:
      - {{cookiecutter.network_name}}
    environment:
      PGPASSWORD: postgres
    command: >
      bash -c '
        echo "CREATE DATABASE {{cookiecutter.database_name}};" | psql -h postgres -U postgres
      '
    depends_on:
      postgres:
        condition: service_healthy

#  opensearch:
#    image: opensearchproject/opensearch:latest
#    networks:
#      - {{cookiecutter.network_name}}
#    ports:
#      - "9200:9200"
#      - "9600:9600"
#    environment:
#      - "cluster.name=opensearch-cluster"
#      - "discovery.type=single-node"
#      - "bootstrap.memory_lock=true"
#      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
#      - "DISABLE_SECURITY_PLUGIN=true"
#      - "DISABLE_INSTALL_DEMO_CONFIG=true"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#      nofile:
#        soft: 65536
#        hard: 65536
#    #volumes:
#    #  - ./opensearch-data:/usr/share/opensearch/data
#
#  opensearch-dashboards:
#    image: opensearchproject/opensearch-dashboards:latest
#    networks:
#      - {{cookiecutter.network_name}}
#    ports:
#      - 5601:5601
#    expose:
#      - "5601"
#    environment:
#      - 'OPENSEARCH_HOSTS=["http://opensearch:9200"]'
#      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"

networks:
  {{cookiecutter.network_name}}:
    name: {{cookiecutter.network_name}}
